# Generated by Django 5.1.5 on 2025-01-20 19:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotionAgentJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("page_id", models.CharField(help_text="Unique identifier of the Notion page", max_length=255)),
                ("parent_page_id", models.CharField(help_text="ID of the parent page in Notion", max_length=255)),
                ("page_url", models.URLField(help_text="URL of the Notion page", max_length=1024)),
                ("description", models.TextField(help_text="Brief description of the page")),
                ("task_details", models.TextField(help_text="Details of what needs to be done")),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("completed", "Completed"), ("failed", "Failed")],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, help_text="Error message if the task failed")),
                ("result", models.TextField(blank=True, help_text="Results or changes made")),
                ("notion_updated_at", models.DateTimeField(help_text="When the page was last updated in Notion")),
                (
                    "created_at",
                    models.DateTimeField(default=django.utils.timezone.now, help_text="When the task was created"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="When the task was last updated")),
                (
                    "completed_at",
                    models.DateTimeField(blank=True, help_text="When the task was completed or failed", null=True),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="notion_noti_status_8fb21d_idx"),
                    models.Index(fields=["page_id"], name="notion_noti_page_id_fdbb76_idx"),
                    models.Index(fields=["parent_page_id"], name="notion_noti_parent__d160c7_idx"),
                ],
            },
        ),
    ]
