# Generated by Django 5.1.5 on 2025-01-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name of the task", max_length=255, unique=True)),
                ("description", models.TextField(blank=True, help_text="Description of what this task does")),
                ("is_active", models.BooleanField(default=True, help_text="Whether this task is enabled")),
                (
                    "notify_on_error",
                    models.BooleanField(default=False, help_text="Whether to send notifications on errors"),
                ),
                ("disable_on_error", models.BooleanField(default=False, help_text="Whether to disable task on errors")),
                ("max_retries", models.IntegerField(default=3, help_text="Maximum number of retry attempts")),
                ("schedule", models.CharField(blank=True, help_text="Crontab or interval schedule", max_length=100)),
                ("last_run", models.DateTimeField(blank=True, null=True)),
                ("next_run", models.DateTimeField(blank=True, null=True)),
                ("config", models.JSONField(default=dict, help_text="Task-specific configuration options")),
                ("error_count", models.IntegerField(default=0, help_text="Number of errors encountered")),
                ("last_error", models.TextField(blank=True, help_text="Last error message")),
                ("last_error_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
    ]
