# Generated by Django 5.1.5 on 2025-01-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notion', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notionagentjob',
            name='parent_page_id',
            field=models.CharField(blank=True, help_text='ID of the parent page in Notion (if any)', max_length=255, null=True),
        ),
    ]
