# Generated by Django 5.1.5 on 2025-01-24 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0006_task_page_blocks"),
    ]

    operations = [
        migrations.CreateModel(
            name="Database",
            fields=[
                ("id", models.CharField(max_length=255, primary_key=True, serialize=False)),
                ("created_time", models.DateTimeField()),
                ("last_edited_time", models.DateTimeField()),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("parent_page_id", models.CharField(max_length=255)),
                ("properties_schema", models.JSONField(default=dict, help_text="Schema of database properties")),
                ("rows", models.JSONField(default=list, help_text="Database rows/items")),
            ],
            options={
                "verbose_name": "Notion Database",
                "verbose_name_plural": "Notion Databases",
            },
        ),
    ]
