# Generated by Django 5.1.5 on 2025-01-27 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0008_database_content_database_embedding_and_more"),
    ]

    operations = [
        # Removed vector index migration since vector_ops is not available
    ]
