# Generated by Django 5.1.5 on 2025-01-27 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0010_auto_20250127_1714"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Page",
        ),
    ]
