# Generated by Django 5.1.5 on 2025-01-27 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0012_page"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="page",
            name="notion_page_title_idx",
        ),
    ]
