# Generated by Django 5.1.5 on 2025-01-27 22:52

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0013_remove_page_notion_page_title_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=1536, help_text="Vector embedding of the content", null=True
            ),
        ),
    ]
