# Generated by Django 5.1.5 on 2025-01-27 23:00

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notion", "0014_alter_page_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="embedding",
            field=pgvector.django.vector.VectorField(
                blank=True, dimensions=384, help_text="Vector embedding of the content", null=True
            ),
        ),
    ]
