# Generated by Django 5.1.5 on 2025-01-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Printer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Printer name (e.g., HP OfficeJet Pro 8720)", max_length=100)),
                ("model", models.CharField(help_text="Model number/name", max_length=100)),
                ("device_name", models.CharField(help_text="Network device name", max_length=100)),
                ("location", models.CharField(help_text="Physical location of printer", max_length=100)),
                (
                    "printer_type",
                    models.CharField(
                        choices=[("INKJET", "Inkjet Printer"), ("THERMAL", "Thermal Printer")],
                        help_text="Type of printer (inkjet, thermal, etc)",
                        max_length=20,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, help_text="IP address for network printing", null=True),
                ),
                ("airprint_enabled", models.BooleanField(default=False, help_text="Whether AirPrint is enabled")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ONLINE", "Online"),
                            ("OFFLINE", "Offline"),
                            ("INK_LOW", "Ink Low"),
                            ("IDLE", "Idle"),
                        ],
                        default="OFFLINE",
                        help_text="Current printer status",
                        max_length=20,
                    ),
                ),
                ("driver_version", models.CharField(blank=True, help_text="Printer driver version", max_length=20)),
                (
                    "default_paper_size",
                    models.CharField(
                        choices=[("LETTER", "Letter (8.5 x 11)"), ("4X6", "Label (4 x 6)")],
                        help_text="Default paper size for this printer",
                        max_length=20,
                    ),
                ),
                ("color_capable", models.BooleanField(default=True, help_text="Whether printer can print in color")),
                (
                    "duplex_capable",
                    models.BooleanField(default=False, help_text="Whether printer supports double-sided printing"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
