# Generated by Django 5.1.5 on 2025-01-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="cups_options",
            field=models.JSONField(default=dict, help_text="Additional CUPS options specific to this printer"),
        ),
        migrations.AddField(
            model_name="printer",
            name="custom_paper_height",
            field=models.IntegerField(blank=True, help_text="Custom paper height in points (1/72 inch)", null=True),
        ),
        migrations.AddField(
            model_name="printer",
            name="custom_paper_width",
            field=models.IntegerField(blank=True, help_text="Custom paper width in points (1/72 inch)", null=True),
        ),
        migrations.AddField(
            model_name="printer",
            name="default_color_model",
            field=models.CharField(
                choices=[("GRAY", "Grayscale"), ("RGB", "Color")],
                default="RGB",
                help_text="Default color mode",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="default_media_type",
            field=models.CharField(
                choices=[
                    ("ANY", "Any"),
                    ("STATIONERY", "Plain Paper"),
                    ("PHOTO_GLOSSY", "Photo Glossy"),
                    ("HEAVY", "Heavy Paper"),
                    ("LIGHT", "Light Paper"),
                    ("CONTINUOUS", "Continuous Paper"),
                    ("LABELS", "Labels"),
                ],
                default="ANY",
                help_text="Default media type",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="default_print_quality",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("NORMAL", "Normal"),
                    ("HIGH", "High"),
                    ("TEXT", "Text Only"),
                    ("GRAPHICS", "Graphics"),
                ],
                default="NORMAL",
                help_text="Default print quality",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="is_default",
            field=models.BooleanField(default=False, help_text="Whether this is the system default printer"),
        ),
        migrations.AddField(
            model_name="printer",
            name="resolution_dpi",
            field=models.IntegerField(default=300, help_text="Print resolution in DPI"),
        ),
        migrations.AddField(
            model_name="printer",
            name="supports_custom_paper_size",
            field=models.BooleanField(default=False, help_text="Whether printer supports custom paper sizes"),
        ),
        migrations.AlterField(
            model_name="printer",
            name="default_paper_size",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter (8.5 x 11)"),
                    ("LETTER_FULL", "Letter Fullbleed"),
                    ("4X6", "Label (4 x 6)"),
                    ("A4", "A4"),
                    ("CUSTOM", "Custom"),
                ],
                help_text="Default paper size for this printer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="device_name",
            field=models.CharField(help_text="Network device name (CUPS name)", max_length=100),
        ),
    ]
