# Generated by Django 5.1.5 on 2025-01-30 20:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0002_printer_cups_options_printer_custom_paper_height_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(help_text="Original name of the file to print", max_length=255)),
                ("file_type", models.CharField(help_text="MIME type or file extension", max_length=50)),
                ("file_size", models.BigIntegerField(help_text="Size of file in bytes")),
                ("file_url", models.URLField(blank=True, help_text="URL for remote files", max_length=500, null=True)),
                ("file_hash", models.CharField(help_text="SHA-256 hash of file for integrity", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        help_text="Current status of the print job",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, help_text="When job started processing", null=True)),
                ("completed_at", models.DateTimeField(blank=True, help_text="When job completed or failed", null=True)),
                ("error_message", models.TextField(blank=True, help_text="Error message if job failed", null=True)),
                ("retry_count", models.IntegerField(default=0, help_text="Number of retry attempts")),
                (
                    "copies",
                    models.IntegerField(
                        default=1,
                        help_text="Number of copies to print",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "paper_size",
                    models.CharField(
                        choices=[
                            ("LETTER", "Letter (8.5 x 11)"),
                            ("LETTER_FULL", "Letter Fullbleed"),
                            ("4X6", "Label (4 x 6)"),
                            ("A4", "A4"),
                            ("CUSTOM", "Custom"),
                        ],
                        help_text="Paper size for this job",
                        max_length=20,
                    ),
                ),
                (
                    "color_mode",
                    models.CharField(
                        choices=[("GRAY", "Grayscale"), ("RGB", "Color")],
                        help_text="Color mode for this job",
                        max_length=20,
                    ),
                ),
                ("duplex", models.BooleanField(default=False, help_text="Whether to print double-sided")),
                (
                    "custom_settings",
                    models.JSONField(default=dict, help_text="Additional printer-specific settings for this job"),
                ),
                (
                    "printer",
                    models.ForeignKey(
                        help_text="Printer to handle this job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_jobs",
                        to="print.printer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Print Job",
                "verbose_name_plural": "Print Jobs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "created_at"], name="print_print_status_bdf99c_idx"),
                    models.Index(fields=["printer", "status"], name="print_print_printer_c1a132_idx"),
                ],
            },
        ),
    ]
