# Generated by Django 5.1.5 on 2025-01-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0003_printjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="aliases",
            field=models.JSONField(default=list, help_text="List of aliases/nicknames for this printer"),
        ),
    ]
