# Generated by Django 5.1.5 on 2025-01-30 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0004_printer_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="printer",
            name="bluetooth_address",
            field=models.CharField(
                blank=True, help_text="Bluetooth MAC address for Bluetooth printers", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="printer",
            name="connection_type",
            field=models.CharField(
                choices=[("CUPS", "CUPS Network Printer"), ("BLUETOOTH", "Bluetooth Device")],
                default="CUPS",
                help_text="How to connect to this printer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="device_name",
            field=models.CharField(help_text="Network device name (CUPS name) or Bluetooth address", max_length=100),
        ),
        migrations.AlterField(
            model_name="printer",
            name="printer_type",
            field=models.CharField(
                choices=[
                    ("INKJET", "Inkjet Printer"),
                    ("THERMAL", "Thermal Printer"),
                    ("BLUETOOTH", "Bluetooth Label Printer"),
                ],
                help_text="Type of printer (e.g., INKJET, THERMAL, BLUETOOTH)",
                max_length=20,
            ),
        ),
    ]
