# Generated by Django 5.1.5 on 2025-02-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("print", "0005_printer_bluetooth_address_printer_connection_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printer",
            name="connection_type",
            field=models.CharField(
                choices=[
                    ("CUPS", "CUPS Network Printer"),
                    ("BLUETOOTH", "Bluetooth Device"),
                    ("USB", "USB Serial Device"),
                ],
                default="CUPS",
                help_text="How to connect to this printer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printer",
            name="default_paper_size",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter (8.5 x 11)"),
                    ("LETTER_FULL", "Letter Fullbleed"),
                    ("LEGAL", "Legal (8.5 x 14)"),
                    ("4X6", "Label (4 x 6)"),
                    ("A4", "A4"),
                    ("LABEL_4XL", "4 x 6 Label"),
                    ("LABEL_12MM", "12mm Label"),
                    ("LABEL_30x15", "30mm x 15mm Label"),
                    ("CUSTOM", "Custom"),
                ],
                help_text="Default paper size for this printer",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="printjob",
            name="paper_size",
            field=models.CharField(
                choices=[
                    ("LETTER", "Letter (8.5 x 11)"),
                    ("LETTER_FULL", "Letter Fullbleed"),
                    ("LEGAL", "Legal (8.5 x 14)"),
                    ("4X6", "Label (4 x 6)"),
                    ("A4", "A4"),
                    ("LABEL_4XL", "4 x 6 Label"),
                    ("LABEL_12MM", "12mm Label"),
                    ("LABEL_30x15", "30mm x 15mm Label"),
                    ("CUSTOM", "Custom"),
                ],
                help_text="Paper size for this job",
                max_length=20,
            ),
        ),
    ]
