# Generated by Django 5.1.5 on 2025-02-03 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("print", "0007_task"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="last_result",
            field=models.JSONField(
                blank=True, help_text="Results from last successful execution (e.g., number of items synced)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="last_run",
            field=models.DateTimeField(blank=True, help_text="Last time the task was run", null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="periodic_task",
            field=models.OneToOneField(
                blank=True,
                help_text="Associated periodic task in Django Celery Beat",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_task",
                to="django_celery_beat.periodictask",
            ),
        ),
    ]
