services:
  web:
    image: coder-app
    build:
      context: ..
      dockerfile: _setup/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    working_dir: /app
    ports:
      - 8000:8000
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app
      - REDIS_HOST=10.16.1.100
      - REDIS_PORT=6379
    depends_on:
      - celery
      - celery-beat

  celery:
    image: coder-app
    build:
      context: ..
      dockerfile: _setup/Dockerfile
    command: celery -A core worker --events -Q default,pfsense_queue,notion_queue,print_queue --loglevel=info
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app
      - OPENAI_API_BASE=http://10.16.1.11:1234
      - REDIS_HOST=10.16.1.100
      - REDIS_PORT=6379

  celery-beat:
    image: coder-app
    build:
      context: ..
      dockerfile: _setup/Dockerfile
    command: celery -A core beat --loglevel=info
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONPATH=/app
      - REDIS_HOST=10.16.1.100
      - REDIS_PORT=6379
    depends_on:
      - celery
