services:
  web:
    build:
      context: ..
      dockerfile: _setup/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ..:/app
    working_dir: /app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app

    depends_on:
      - redis
      - celery
      - celery-beat

  celery:
    build:
      context: ..
      dockerfile: _setup/Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app
      - OPENAI_API_BASE=http://10.16.1.11:1234
    depends_on:
      - redis

  celery-beat:
    build:
      context: ..
      dockerfile: _setup/Dockerfile
    command: celery -A core beat --loglevel=info
    volumes:
      - ..:/app
    working_dir: /app
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PYTHONPATH=/app
    depends_on:
      - redis
      - celery

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
