analyze_note:
  description: >
    Analyze a Notion page to determine if it needs organization:
    1. Check if the title starts with "CLEAN"
    2. Look for callouts with 💡 icon that start with "Notey"
    3. Extract any specific organization or formatting instructions
    4. Identify the main topics and categories of the content
    5. Determine if this note could be combined with other related notes
  expected_output: >
    Analysis of the page including whether it needs organization, any specific instructions found, 
    and recommendations for categorization and potential note combinations.
  agent: notes_organizer

create_note:
  description: >
    Create a new Notion page with the specified title and content.
  expected_output: >
    A new Notion page with the specified title and content.
  agent: notes_organizer
