# Generated by Django 5.1.5 on 2025-02-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EasyPostAccountModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "account_name",
                    models.CharField(help_text="Unique name for the EasyPost account", max_length=255, unique=True),
                ),
                ("email", models.EmailField(help_text="Email associated with the EasyPost account", max_length=254)),
                (
                    "api_key_name",
                    models.CharField(
                        help_text="Name used to store/retrieve API key from vault", max_length=255, unique=True
                    ),
                ),
                (
                    "vault_path",
                    models.CharField(
                        blank=True, help_text="Full path where the API key is stored in vault", max_length=512
                    ),
                ),
                (
                    "account_id",
                    models.CharField(blank=True, help_text="EasyPost account ID retrieved from API", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "EasyPost Account",
                "verbose_name_plural": "EasyPost Accounts",
            },
        ),
    ]
