# Generated by Django 5.1.5 on 2025-02-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0002_easypostaccountmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="easypostaccountmodel",
            name="is_default",
            field=models.BooleanField(default=False, help_text="Whether this is the default EasyPost account"),
        ),
    ]
