# Generated by Django 5.1.5 on 2025-02-20 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipper", "0003_easypostaccountmodel_is_default"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="Name for this address", max_length=255)),
                ("company", models.CharField(blank=True, help_text="Company name", max_length=255)),
                ("street1", models.CharField(help_text="Street address line 1", max_length=255)),
                ("street2", models.CharField(blank=True, help_text="Street address line 2", max_length=255)),
                ("city", models.CharField(help_text="City", max_length=255)),
                ("state", models.CharField(help_text="State (2-letter code)", max_length=2)),
                ("zip_code", models.CharField(help_text="ZIP code", max_length=10)),
                ("country", models.CharField(default="US", help_text="Country code (2-letter)", max_length=2)),
                ("phone", models.CharField(blank=True, help_text="Phone number", max_length=20)),
                ("email", models.EmailField(blank=True, help_text="Email address", max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "default_ship_from_for",
                    models.ForeignKey(
                        blank=True,
                        help_text="EasyPost account that uses this as default ship-from address",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="default_ship_from_address",
                        to="shipper.easypostaccountmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
                "indexes": [
                    models.Index(fields=["name"], name="shipper_add_name_64f9b3_idx"),
                    models.Index(fields=["zip_code"], name="shipper_add_zip_cod_8e6ee4_idx"),
                ],
            },
        ),
    ]
