clean_up_my_notes:
  description: >
    Notey, I need you to clean up my Notion workspace specically the subpages found in Notes -> Crazy Notes (page id: 17d91679-55c8-801a-9db4-c88a23703a58). 
    Clean the notes found in the subpages, combine them ONLY if they are related to the same topic and organize them in Notes -> Clean Notes subpages. Once you are done and verified the notes are cleaned up you can delete the notes you combined, and move on to the next subpage.
  expected_output: >
    All notes(subpages) in the Crazy Notes subpages have been cleaned up and organized in Notes -> Clean Notes subpages.
  agent: notes_organizer