# Generated by Django 5.1.5 on 2025-02-03 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pfsense", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DHCPRoutes",
            new_name="DHCPRoute",
        ),
    ]
