# Generated by Django 5.1.5 on 2025-02-05 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfsense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskerror",
            name="status",
            field=models.CharField(
                choices=[("new", "New"), ("ongoing", "Ongoing"), ("regressed", "Regressed"), ("cleared", "Cleared")],
                default="new",
                help_text="Current status of the error",
                max_length=20,
            ),
        ),
    ]
