# Generated by Django 5.1.5 on 2025-02-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pfsense", "0002_rename_dhcproutes_dhcproute"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tasks",
            options={"ordering": ["name"], "verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="config",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="error_count",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="last_error",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="last_error_time",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="next_run",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="updated_at",
        ),
    ]
