# Generated by Django 5.1.5 on 2025-02-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfsense", "0002_taskerror_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dhcproute",
            name="network",
            field=models.CharField(help_text="Network address (IPv4/IPv6)", max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name="dhcproute",
            name="pfsense_id",
            field=models.CharField(help_text="ID of the route in pfSense", max_length=100),
        ),
    ]
