# Generated by Django 5.1.5 on 2025-02-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfsense", "0003_alter_tasks_options_remove_tasks_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcproute",
            name="hostname",
            field=models.CharField(blank=True, help_text="Hostname for the route", max_length=255),
        ),
    ]
