# Generated by Django 5.1.5 on 2025-02-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfsense", "0003_alter_dhcproute_network_alter_dhcproute_pfsense_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dhcproute",
            name="online_status",
            field=models.CharField(blank=True, choices=[("active", "Active"), ("inactive", "Inactive")], max_length=20),
        ),
    ]
