# Generated by Django 5.1.5 on 2025-02-03 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("pfsense", "0005_tasks_last_error_tasks_last_result_tasks_last_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_active", models.BooleanField(default=True)),
                ("name", models.CharField(help_text="Name of the task", max_length=255, unique=True)),
                ("description", models.TextField(blank=True, help_text="Description of what this task does")),
                (
                    "notify_on_error",
                    models.BooleanField(default=False, help_text="Whether to send notifications on errors"),
                ),
                ("disable_on_error", models.BooleanField(default=False, help_text="Whether to disable task on errors")),
                ("max_retries", models.IntegerField(default=3, help_text="Maximum number of retry attempts")),
                ("schedule", models.CharField(blank=True, help_text="Crontab or interval schedule", max_length=100)),
                ("last_run", models.DateTimeField(blank=True, help_text="Last time the task was run", null=True)),
                ("next_run", models.DateTimeField(blank=True, help_text="Next scheduled run time", null=True)),
                (
                    "last_status",
                    models.CharField(
                        blank=True,
                        choices=[("success", "Success"), ("error", "Error")],
                        help_text="Status of the last execution",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "last_result",
                    models.JSONField(
                        blank=True,
                        help_text="Results from last successful execution (e.g., number of items synced)",
                        null=True,
                    ),
                ),
                ("last_error", models.TextField(blank=True, help_text="Error message from last failed execution")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "periodic_task",
                    models.OneToOneField(
                        blank=True,
                        help_text="Associated periodic task in Django Celery Beat",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_task",
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.DeleteModel(
            name="Tasks",
        ),
    ]
