# Generated by Django 5.1.5 on 2025-02-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfsense", "0006_task_delete_tasks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["name"], "verbose_name": "Task", "verbose_name_plural": "Tasks"},
        ),
        migrations.RemoveField(
            model_name="task",
            name="next_run",
        ),
        migrations.AlterField(
            model_name="task",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Whether this task is active"),
        ),
        migrations.AlterField(
            model_name="task",
            name="schedule",
            field=models.CharField(blank=True, help_text="Human-readable schedule description", max_length=100),
        ),
    ]
