# Generated by Django 5.1.5 on 2025-02-18 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adwords", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "customer_id",
                    models.CharField(help_text="Manager Account ID (format: XXX-XXX-XXXX)", max_length=12, unique=True),
                ),
                ("name", models.CharField(help_text="Account descriptive name", max_length=255)),
                ("currency_code", models.CharField(help_text="Account currency code (e.g., USD)", max_length=3)),
                ("time_zone", models.CharField(help_text="Account timezone", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Manager Account",
                "verbose_name_plural": "Manager Accounts",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClientAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "customer_id",
                    models.CharField(help_text="Client Account ID (format: XXX-XXX-XXXX)", max_length=12, unique=True),
                ),
                ("name", models.CharField(help_text="Account descriptive name", max_length=255)),
                ("currency_code", models.CharField(help_text="Account currency code (e.g., USD)", max_length=3)),
                ("time_zone", models.CharField(help_text="Account timezone", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "daily_budget",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Daily budget in account currency",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "website_url",
                    models.URLField(blank=True, help_text="Primary website URL", max_length=255, null=True),
                ),
                (
                    "business_name",
                    models.CharField(
                        blank=True, help_text="Business name associated with this account", max_length=255, null=True
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        help_text="Manager account that owns this client account",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="clients",
                        to="adwords.manageraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Client Account",
                "verbose_name_plural": "Client Accounts",
                "ordering": ["name"],
            },
        ),
    ]
