# Generated by Django 5.1.5 on 2025-02-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adwords", "0002_manageraccount_clientaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageraccount",
            name="vault_key",
            field=models.CharField(
                blank=True,
                help_text="Key used to store developer token in vault (e.g., manager_288244783)",
                max_length=100,
                null=True,
                unique=True,
            ),
        ),
    ]
