# Generated by Django 5.1.5 on 2025-02-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adwords", "0003_manageraccount_vault_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manageraccount",
            name="currency_code",
            field=models.CharField(blank=True, help_text="Account currency code (e.g., USD)", max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="manageraccount",
            name="time_zone",
            field=models.CharField(blank=True, help_text="Account timezone", max_length=50, null=True),
        ),
    ]
