# Generated by Django 5.1.5 on 2025-02-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adwords", "0004_alter_manageraccount_currency_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="manageraccount",
            name="description",
            field=models.TextField(blank=True, help_text="Account description", null=True),
        ),
    ]
