# Generated by Django 5.1.5 on 2025-02-09 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("twilio_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="twilioaccount",
            options={"ordering": ["name"], "verbose_name": "Twilio Account", "verbose_name_plural": "Twilio Accounts"},
        ),
        migrations.RemoveField(
            model_name="twilioaccount",
            name="phone_numbers",
        ),
        migrations.CreateModel(
            name="TwilioPhoneNumber",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sid", models.CharField(help_text="Twilio Phone Number SID", max_length=34, unique=True)),
                ("phone_number", models.CharField(help_text="Phone number in E.164 format", max_length=20)),
                ("friendly_name", models.CharField(help_text="Friendly name for the phone number", max_length=100)),
                ("capability_voice", models.BooleanField(default=False)),
                ("capability_sms", models.BooleanField(default=False)),
                ("capability_mms", models.BooleanField(default=False)),
                ("capability_fax", models.BooleanField(default=False)),
                ("api_version", models.CharField(help_text="Twilio API version", max_length=20)),
                ("voice_url", models.URLField(blank=True, max_length=255, null=True)),
                ("voice_method", models.CharField(default="POST", max_length=10)),
                ("voice_fallback_url", models.URLField(blank=True, max_length=255, null=True)),
                ("voice_fallback_method", models.CharField(default="POST", max_length=10)),
                ("status_callback", models.URLField(blank=True, max_length=255, null=True)),
                ("status_callback_method", models.CharField(default="POST", max_length=10)),
                ("voice_caller_id_lookup", models.BooleanField(default=False)),
                ("sms_url", models.URLField(blank=True, max_length=255, null=True)),
                ("sms_method", models.CharField(default="POST", max_length=10)),
                ("sms_fallback_url", models.URLField(blank=True, max_length=255, null=True)),
                ("sms_fallback_method", models.CharField(default="POST", max_length=10)),
                ("address_requirements", models.CharField(default="none", max_length=20)),
                ("emergency_status", models.CharField(max_length=20)),
                ("emergency_address_sid", models.CharField(blank=True, max_length=34, null=True)),
                ("address_sid", models.CharField(blank=True, max_length=34, null=True)),
                ("bundle_sid", models.CharField(blank=True, max_length=34, null=True)),
                ("identity_sid", models.CharField(blank=True, max_length=34, null=True)),
                ("trunk_sid", models.CharField(blank=True, max_length=34, null=True)),
                ("origin", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("date_created", models.DateTimeField()),
                ("date_updated", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        help_text="Associated Twilio account",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phone_numbers",
                        to="twilio_app.twilioaccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Twilio Phone Number",
                "verbose_name_plural": "Twilio Phone Numbers",
                "ordering": ["phone_number"],
                "indexes": [
                    models.Index(fields=["phone_number"], name="twilio_app__phone_n_082f70_idx"),
                    models.Index(fields=["account", "status"], name="twilio_app__account_f6d546_idx"),
                ],
            },
        ),
    ]
